/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package revolut;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Kannan
 */
public class currency extends javax.swing.JFrame {
    
        double indian_rp = 76.45;
        double Rus_ruby  = 67.70;
        double ameri_doll = 1.24;
        double britain_pond = 0.89;
        double canadian_doll = 1.47;
        double jap_yen = 132.19;
        
    /**
     * Creates new form currency
     */
    public currency() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jcountry = new javax.swing.JComboBox<>();
        jinput = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        acno = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        joutput = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel1.setText("Currency converter");

        jcountry.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose One...", "Indian Rupees", "American dollars", "Russian ruble", "Birtish Pounds", "Canadian dollar", "Japanese yen" }));

        jinput.setText("0");
        jinput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jinputActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Euro");

        acno.setText("jLabel3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(jinput, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)))
                .addContainerGap(47, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jcountry, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(acno)
                .addGap(59, 59, 59))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(acno)
                .addGap(8, 8, 8)
                .addComponent(jcountry, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jinput, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        joutput.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton1.setText("Convert");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(joutput, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jButton1)
                        .addGap(62, 62, 62)
                        .addComponent(jButton2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(45, 45, 45))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(joutput, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(408, 388));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jinputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jinputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jinputActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jcountry.setSelectedIndex(0);
        jinput.setText(null);
        joutput.setText(null);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        
        
        try {
            
        
       
                double euro=0;
                double ind=0;
                double rus=0;
                double usa=0;
                double bri=0;
                double can=0;
                double jap=0;
               String vale="0";
                String vali="0";
                String valr="0";
                String vala="0";
                String valc="0";
                String valb="0";
                String valj="0";
                
        String  converte,converti,converta,convertr,convertc,convertb,convertj;
        double  cone,coni,cona,conr,conc,conb,conj;
            balance bl =new balance();
            int acc = Integer.parseInt(this.acno.getText());
            Statement stmt;
            Connection con;
            try {
                 con =DriverManager.getConnection("jdbc:derby://localhost:1527/RevolutDB","kannan","kannan");
                 stmt = con.createStatement();
        
        String dbq = "Select europe,india,us,canada,british,russia,japan from KANNAN.balance  where acc_no = "+acc+"";
       
        ResultSet rs1 = stmt.executeQuery(dbq);
        if(rs1.next())
        {
            vale = rs1.getString("europe");
           
            vali = rs1.getString("india");
            
            valr = rs1.getString("russia");
            
            vala = rs1.getString("us");
           
            valc = rs1.getString("canada");
            
            valb = rs1.getString("british");
            
            valj = rs1.getString("japan");
            
            
        }
            } catch (SQLException ex) {
               // Logger.getLogger(currency.class.getName()).log(Level.SEVERE, null, ex);
               System.err.println(ex);
            }
            
            euro = Double.parseDouble(vale);
            ind = Double.parseDouble(vali);
            rus = Double.parseDouble(valr);
           usa = Double.parseDouble(vala);
           can = Double.parseDouble(valc);
           bri = Double.parseDouble(valb);
           jap = Double.parseDouble(valj);
            
          
            double inp = Double.parseDouble(jinput.getText());
            
            
        
         if( inp>= 0 && inp <= 1000 && inp <= euro  )   
         {
        //double euro = Double.parseDouble(jinput.getText());
             double eur1 = (euro - inp); 
             //converte = Double.toString(eur1);
        try {
        if (jcountry.getSelectedItem().equals("Indian Rupees"))
        {
            ind = (inp * indian_rp)+ind ;
            String convert = String.format("₹ %.2f", (inp * indian_rp) );            
            joutput.setText(convert);
            
        }
        else if (jcountry.getSelectedItem().equals("American dollars"))
        {
            usa =(inp * ameri_doll)+usa;
            String convert = String.format("$ %.2f", (inp * ameri_doll) );
            joutput.setText(convert);
        }
        else if (jcountry.getSelectedItem().equals("Russian ruble"))
        {
            rus=(inp * Rus_ruby)+rus;
            String convert = String.format("₽ %.2f", (inp * Rus_ruby) );
            joutput.setText(convert);
        }
        else if (jcountry.getSelectedItem().equals("Birtish Pounds"))
        {
            bri = (inp * britain_pond)+bri;
            String convert = String.format("£ %.2f", (inp * britain_pond) );
            joutput.setText(convert);
        }
        else if (jcountry.getSelectedItem().equals("Canadian dollar"))
        {
            can = (inp * canadian_doll)+can;
            String convert = String.format("$ %.2f", (inp * canadian_doll) );
            joutput.setText(convert);
        }
        else if (jcountry.getSelectedItem().equals("Japanese yen"))
        {
            jap = (inp * jap_yen)+jap;
            String convert = String.format("¥ %.2f", (inp * jap_yen) );
            joutput.setText(convert);
        }
        try {
       Connection con1 =DriverManager.getConnection("jdbc:derby://localhost:1527/RevolutDB","kannan","kannan");
        Statement stmt1 = con1.createStatement();
        String d1 =  Double.toString(eur1);
        String upt = "update KANNAN.balance set europe = '"+Double.toString(eur1)+"',india = '"+Double.toString(ind)+"',us = '"+Double.toString(usa)+"',canada = '"+Double.toString(can)+"',british = '"+Double.toString(bri)+"',russia = '"+Double.toString(rus)+"',japan = '"+Double.toString(jap)+"' where acc_no = "+acc+"";                 
        int in =stmt1.executeUpdate(upt);
                 } catch (SQLException ex) {
                     //Logger.getLogger(currency.class.getName()).log(Level.SEVERE, null, ex);
                     
                     System.err.println(ex);
                 }
            
        } catch (NumberFormatException e) {
                 JOptionPane.showMessageDialog(null, "Please check the inputs");
                  System.err.println(e);
         }
        
    }//GEN-LAST:event_jButton1ActionPerformed
    else
    {
    JOptionPane.showMessageDialog(null, "no sufficient balance");
            }
     } catch (Exception e) {
              System.err.println(e);
        }
    
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(currency.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(currency.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(currency.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(currency.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new currency().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel acno;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> jcountry;
    private javax.swing.JTextField jinput;
    private javax.swing.JLabel joutput;
    // End of variables declaration//GEN-END:variables
}
